#!/bin/bash
set -e # fail on any error
set -u # treat unset variables as errors

# ======[ Trap Errors ]======#
set -E # let shell functions inherit ERR trap

# Trap non-normal exit signals:
# 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
trap err_handler 1 2 3 15 ERR
function err_handler {
local exit_status=${1:-$?}
logger -s -p "syslog.err" -t "dslideshow.deb" "dslideshow.deb script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
exit $exit_status
}

# Give the pi permission to use 3D acceleration.
sudo usermod -a -G render pi

sudo systemctl enable dslideshow
#sudo systemctl start dslideshow

# Update the system fonts.
sudo fc-cache

# Create links

if [ -e /usr/lib/icudtl.dat ]
then
# если файл существует, добавить в него данные
  sudo rm /usr/lib/icudtl.dat
fi
sudo ln -s -f /opt/dslideshow/flutter_assets/icudtl.dat /usr/lib/icudtl.dat

# https://www.raspberryconnect.com/projects/65-raspberrypi-hotspot-accesspoints/157-raspberry-pi-auto-wifi-hotspot-switch-internet
#sudo systemctl unmask hostapd
#sudo systemctl disable hostapd
#sudo systemctl disable dnsmasq

#sudo systemctl enable autohotspot

exit 0

