name: 'autover'
version: 1.0.0
description: An absolute bare-bones web app.
author: Igor Demyanov

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: ^0.11.0
  yaml: ^2.2.1
  pub_semver: ^1.4.4
  args: ^1.6.0
  path: ^1.7.0