name: 'autover'
version: 1.0.2
description: Auto version increment. Auto-increment version in pubspec.yaml for multiple projects. It generate file by template with projects versions
homepage: https://github.com/DisDis/dslideshow/tree/master/autover


environment:
  sdk: '^3.0.0'

dependencies:
  logging: ^1.2.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  args: ^2.4.2
  path: ^1.8.3

# dev_dependencies:
#     pedantic: ^1.9.0