name: 'autover'
version: 2.0.0
description: Auto version increment. Auto-increment version in pubspec.yaml for multiple projects. It generate file by template with projects versions
homepage: https://github.com/DisDis/dslideshow/tree/master/autover


environment:
  sdk: '^3.0.0'

dependencies:
  logging: ^1.2.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  args: ^2.4.2
  path: ^1.8.3

#dev_dependencies:
#  dart_code_metrics_presets: ^2.6.0
#  very_good_analysis: ^5.1.0