name: media_slider_widget
description: Widget to show the media items in slider
version: 0.0.1
author: andrey smirnov [guid.empty]
homepage: https://github.com/guid-empty

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
